//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskNLearn : DbContext
    {
        public AskNLearn()
            : base("name=AskNLearn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<EnrolledUser> EnrolledUsers { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Quize> Quizes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInfo> UsersInfoes { get; set; }
    }
}
